# default login
# admin:admin
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  JUMPHOST: "jumphost.example.com"
  MYSQL_DATABASE: "beaker"
  MYSQL_USER: "beaker"
  MYSQL_PASSWORD: "beaker"
  MYSQL_ROOT_PASSWORD: "password"
  MYSQL_CHARSET: "utf8"
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: beaker
  name: beaker
spec:
  containers:
    - image: "docker.io/mariadb:10.3"
      name: db
      envFrom:
      - configMapRef:
          name: config
      volumeMounts:
        - mountPath: "/var/lib/mysql:z"
          name: db-volume
    - image: "quay.io/distributedci/beaker-server:latest"
      name: server
      ports:
      - containerPort: 80
        hostPort: 8001
        protocol: TCP
      envFrom:
      - configMapRef:
          name: config
      volumeMounts:
        - mountPath: "/data:z"
          name: beaker-data-volume
        - mountPath: "/config:z"
          name: config-volume
    - image: "quay.io/distributedci/beaker-lab-controller:latest"
      name: lab-controller
      ports:
      - containerPort: 8000
        hostPort: 8000
        protocol: TCP
      envFrom:
      - configMapRef:
          name: config
      volumeMounts:
        - mountPath: "/data:z"
          name: beaker-data-volume
        - mountPath: "/config:z"
          name: config-volume
        - mountPath: "/var/lib/tftpboot:z"
          name: tftp-volume
        - mountPath: "/etc/dci-rhel-agent/secrets"
          name: secrets-volume
  volumes:
    - name: db-volume
      emptyDir: {}
    - name: beaker-data-volume
      emptyDir: {}
    - name: config-volume
      emptyDir: {}
    - name: tftp-volume
      emptyDir: {}
    - name: secrets-volume
      emptyDir: {}
  restartPolicy: OnFailure
